### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by zhangzhiyi0108** [Frozenmad/AMN_SRL#2]
def _get_actual_sentence_from_train(self,id):
        return ' '.join(list(map(lambda x:x[5],self.old_train[id])))这个函数运行结果报错说超出范围是怎么回事
Traceback (most recent call last):
  File "/home/zutnlp/zhangzhiyi/AMN_SRL/main.py", line 45, in <module>
    all_data = final_dataset(train_input_file,dev_input_file,test_input_file,aug_num,'temp/train_train.bin','temp/train_dev.bin','temp/train_test.bin')
  File "/home/zutnlp/zhangzhiyi/AMN_SRL/final_inter_helper.py", line 56, in __init__
    self._load_new()
  File "/home/zutnlp/zhangzhiyi/AMN_SRL/final_inter_helper.py", line 71, in _load_new
    if self._get_actual_sentence_from_train(sort_sentence_id) != self._get_actual_sentence_from_train(i):
  File "/home/zutnlp/zhangzhiyi/AMN_SRL/final_inter_helper.py", line 96, in _get_actual_sentence_from_train
    return ' '.join(list(map(lambda x:x[0],self.old_train[id])))
IndexError: list index out of range

**Comment by Frozenmad** [comment]
一般不应该出现这个错误呀，能否检查一下您的/temp/train.flat.txt, /temp/dev.flat.txt 和 /temp/test.flat.txt生成过程是否有误，生成的结果是否每一行都是十个元素。如果您生成的x.flat.txt是正确的，那么它的每一行包含的内容应该和[这里](https://github.com/Frozenmad/AMN_SRL/blob/ffa87f9809045605b092e2b24082619c648899de/data_utils.py#L536)一样。您报错的函数是试图获得每一行的第6个元素（也就是word）并将它们连成一句话。

**Comment by zhangzhiyi0108** [comment]
我看了数据，和您说的格式是一样的，但是还是运行不了

**Comment by Frozenmad** [comment]
您好，我在本地测试了一下好像没有发现问题。请再次检查**原始数据格式是否正确**，以及您是否**按照readme中的指示处理数据**。

我们的预处理流程是：
1. `preprocess.py`来对原始格式的数据集进行重编码，并提取数据集相关信息。
2. `edit_dis.py`来计算train dev test中两句话之间的距离信息并保存。

请再次确保第一步之后生成的`/temp/train.flat.txt`, `/temp/dev.flat.txt`以及`/temp/test.flat.txt` （注意不是原始数据集）每行10个元素。像如下例子一样：
```
0       0       25      1       0       the     the     DT      NMOD    _
0       0       25      2       0       economy economy NN      NMOD    A1
0       0       25      3       0       's      's      POS     SUFFIX  _
0       0       25      4       1       temperature     temperature     NN      SBJ     A2
0       0       25      5       0       will    will    MD      ROOT    _
0       0       25      6       0       be      be      VB      VC      _
0       0       25      7       0       taken   take    VBN     VC      _
0       0       25      8       0       from    from    IN      ADV     _
0       0       25      9       0       several several DT      NMOD    _
0       0       25      10      0       vantage vantage NN      NMOD    _
0       0       25      11      0       points  point   NNS     PMOD    _
0       0       25      12      0       this    this    DT      NMOD    _
0       0       25      13      0       week    week    NN      TMP     _
0       0       25      14      0       ,       ,       ,       P       _
0       0       25      15      0       with    with    IN      ADV     _
0       0       25      16      0       readings        reading NNS     PMOD    _
0       0       25      17      0       on      on      IN      NMOD    _
0       0       25      18      0       trade   trade   NN      PMOD    _
0       0       25      19      0       ,       ,       ,       P       _
0       0       25      20      0       output  output  NN      COORD   _
0       0       25      21      0       ,       ,       ,       P       _
0       0       25      22      0       housing housing NN      COORD   _
0       0       25      23      0       and     and     CC      COORD   _
0       0       25      24      0       inflation       inflation       NN      CONJ    _
0       0       25      25      0       .       .       .       P       _

0       1       25      1       0       the     the     DT      NMOD    _
0       1       25      2       0       economy economy NN      NMOD    _
0       1       25      3       0       's      's      POS     SUFFIX  _
0       1       25      4       0       temperature     temperature     NN      SBJ     A1
0       1       25      5       0       will    will    MD      ROOT    AM-MOD
0       1       25      6       0       be      be      VB      VC      _
0       1       25      7       1       taken   take    VBN     VC      _
0       1       25      8       0       from    from    IN      ADV     A2
0       1       25      9       0       several several DT      NMOD    _
0       1       25      10      0       vantage vantage NN      NMOD    _
0       1       25      11      0       points  point   NNS     PMOD    _
0       1       25      12      0       this    this    DT      NMOD    _
0       1       25      13      0       week    week    NN      TMP     AM-TMP
0       1       25      14      0       ,       ,       ,       P       _
0       1       25      15      0       with    with    IN      ADV     AM-ADV
0       1       25      16      0       readings        reading NNS     PMOD    _
0       1       25      17      0       on      on      IN      NMOD    _
0       1       25      18      0       trade   trade   NN      PMOD    _
0       1       25      19      0       ,       ,       ,       P       _
0       1       25      20      0       output  output  NN      COORD   _
0       1       25      21      0       ,       ,       ,       P       _
0       1       25      22      0       housing housing NN      COORD   _
0       1       25      23      0       and     and     CC      COORD   _
0       1       25      24      0       inflation       inflation       NN      CONJ    _
0       1       25      25      0       .       .       .       P       _

...
```

如果错误依然出现，您可以将代码、数据通过邮件的方式共享给我，不过我还在读书所以可能不会及时回复，请谅解0.0
